//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingV2.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int ID_EMPLOYEE { get; set; }
        public string EMPLOYEE_FIRSTNAME { get; set; }
        public string EMPLOYEE_LASTNAME { get; set; }
        public string EMPLOYEE_USERNAME { get; set; }
        public string EMPLOYEE_PASSWORD { get; set; }
        public bool EST_ADMIN { get; set; }
        public int ID_CIVILITE { get; set; }
    
        public virtual CIVILITE CIVILITE { get; set; }
    }
}
