//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingV2.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANISATION
    {
        public int ID_ORG { get; set; }
        public string NAME_ORG { get; set; }
        public string URL_ORG { get; set; }
        public string EMAIL_ORG { get; set; }
        public string TEL_ORG { get; set; }
        public string ADRESS_ORG { get; set; }
        public int ID_CASTING { get; set; }
        public int ID_PACK { get; set; }
    
        public virtual CASTING CASTING { get; set; }
        public virtual PACK PACK { get; set; }
    }
}
