//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingV2.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CASTINGS = new HashSet<CASTING>();
        }
    
        public int ID_USER { get; set; }
        public string USER_FIRSTNAME { get; set; }
        public string USER_LASTNAME { get; set; }
        public string USERNAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_MAIL { get; set; }
        public System.DateTime USER_NAISSANCE { get; set; }
        public string IMG_PROFIL { get; set; }
        public int ID_CIVILITE { get; set; }
    
        public virtual CIVILITE CIVILITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASTING> CASTINGS { get; set; }
    }
}
