CREATE TABLE [dbo].[APPARTENIR_FILTRE] (
    [ID_CASTING] INT NOT NULL,
    [ID_FILTRE]  INT NOT NULL,
    CONSTRAINT [APPARTENIR_FILTRE_PK] PRIMARY KEY CLUSTERED ([ID_CASTING] ASC, [ID_FILTRE] ASC),
    CONSTRAINT [APPARTENIR_FILTRE_CASTINGS_FK] FOREIGN KEY ([ID_CASTING]) REFERENCES [dbo].[CASTINGS] ([ID_CASTING]),
    CONSTRAINT [APPARTENIR_FILTRE_FILTRES0_FK] FOREIGN KEY ([ID_FILTRE]) REFERENCES [dbo].[FILTRES] ([ID_FILTRE])
);

