CREATE TABLE [dbo].[APPARTIENT_CASTING] (
    [ID_CASTING] INT NOT NULL,
    [ID_CAT]     INT NOT NULL,
    CONSTRAINT [APPARTIENT_CASTING_PK] PRIMARY KEY CLUSTERED ([ID_CASTING] ASC, [ID_CAT] ASC),
    CONSTRAINT [APPARTIENT_CASTING_CASTINGS_FK] FOREIGN KEY ([ID_CASTING]) REFERENCES [dbo].[CASTINGS] ([ID_CASTING]),
    CONSTRAINT [APPARTIENT_CASTING_CATEGORIES0_FK] FOREIGN KEY ([ID_CAT]) REFERENCES [dbo].[CATEGORIES] ([ID_CAT])
);

