CREATE TABLE [dbo].[CASTINGS] (
    [ID_CASTING]        INT          IDENTITY (1, 1) NOT NULL,
    [LABEL]             VARCHAR (50) NULL,
    [DOM_METIERS]       VARCHAR (50) NULL,
    [METIERS]           VARCHAR (50) NOT NULL,
    [TYPE_CONTRACT]     VARCHAR (50) NOT NULL,
    [DUREE_DIFFUSION]   INT          NULL,
    [DATE_DEB_CONTRACT] DATETIME     NOT NULL,
    [NB_POSTES]         INT          NOT NULL,
    [LOCALISATION]      VARCHAR (50) NOT NULL,
    [DESC_POSTE]        TEXT         NULL,
    [DESC_PROFIL]       TEXT         NULL,
    [COORDONNEES]       VARCHAR (50) NULL,
    CONSTRAINT [CASTINGS_PK] PRIMARY KEY CLUSTERED ([ID_CASTING] ASC)
);

