CREATE TABLE [dbo].[CATEGORIES] (
    [ID_CAT]    INT             IDENTITY (1, 1) NOT NULL,
    [CAT_LABEL] VARCHAR (50)    NULL,
    [IMG_CAST]  NVARCHAR (2000) NULL,
    CONSTRAINT [CATEGORIES_PK] PRIMARY KEY CLUSTERED ([ID_CAT] ASC)
);



