CREATE TABLE [dbo].[CIVILITE] (
    [ID_CIVILITE]    INT          IDENTITY (1, 1) NOT NULL,
    [LABEL_CIVILITE] VARCHAR (50) NOT NULL,
    CONSTRAINT [CIVILITE_PK] PRIMARY KEY CLUSTERED ([ID_CIVILITE] ASC)
);

