CREATE TABLE [dbo].[EMPLOYEE] (
    [ID_EMPLOYEE]        INT           IDENTITY (1, 1) NOT NULL,
    [EMPLOYEE_FIRSTNAME] VARCHAR (100) NOT NULL,
    [EMPLOYEE_LASTNAME]  VARCHAR (100) NOT NULL,
    [EMPLOYEE_USERNAME]  VARCHAR (150) NOT NULL,
    [EMPLOYEE_PASSWORD]  VARCHAR (175) NOT NULL,
    [EST_ADMIN]          BIT           NOT NULL,
    [ID_CIVILITE]        INT           NOT NULL,
    CONSTRAINT [EMPLOYEE_PK] PRIMARY KEY CLUSTERED ([ID_EMPLOYEE] ASC),
    CONSTRAINT [EMPLOYEE_CIVILITE_FK] FOREIGN KEY ([ID_CIVILITE]) REFERENCES [dbo].[CIVILITE] ([ID_CIVILITE])
);

