CREATE TABLE [dbo].[FILTRES] (
    [ID_FILTRE]    INT          IDENTITY (1, 1) NOT NULL,
    [CAT_LABEL]    VARCHAR (50) NULL,
    [LABEL_FILTRE] VARCHAR (75) NOT NULL,
    CONSTRAINT [FILTRES_PK] PRIMARY KEY CLUSTERED ([ID_FILTRE] ASC)
);

