CREATE TABLE [dbo].[ORGANISATION] (
    [ID_ORG]     INT            IDENTITY (1, 1) NOT NULL,
    [NAME_ORG]   VARCHAR (150)  NOT NULL,
    [URL_ORG]    VARCHAR (1000) NOT NULL,
    [EMAIL_ORG]  VARCHAR (100)  NULL,
    [TEL_ORG]    VARCHAR (50)   NOT NULL,
    [ADRESS_ORG] VARCHAR (100)  NULL,
    [ID_CASTING] INT            NOT NULL,
    [ID_PACK]    INT            NOT NULL,
    CONSTRAINT [ORGANISATION_PK] PRIMARY KEY CLUSTERED ([ID_ORG] ASC),
    CONSTRAINT [ORGANISATION_CASTINGS_FK] FOREIGN KEY ([ID_CASTING]) REFERENCES [dbo].[CASTINGS] ([ID_CASTING]),
    CONSTRAINT [ORGANISATION_PACK0_FK] FOREIGN KEY ([ID_PACK]) REFERENCES [dbo].[PACK] ([ID_PACK])
);

