CREATE TABLE [dbo].[POSTULER] (
    [ID_CASTING] INT NOT NULL,
    [ID_USER]    INT NOT NULL,
    CONSTRAINT [POSTULER_PK] PRIMARY KEY CLUSTERED ([ID_CASTING] ASC, [ID_USER] ASC),
    CONSTRAINT [POSTULER_CASTINGS_FK] FOREIGN KEY ([ID_CASTING]) REFERENCES [dbo].[CASTINGS] ([ID_CASTING]),
    CONSTRAINT [POSTULER_USERS0_FK] FOREIGN KEY ([ID_USER]) REFERENCES [dbo].[USERS] ([ID_USER])
);

