CREATE TABLE [dbo].[USERS] (
    [ID_USER]        INT             NOT NULL,
    [USER_FIRSTNAME] VARCHAR (100)   NULL,
    [USER_LASTNAME]  VARCHAR (100)   NOT NULL,
    [USERNAME]       VARCHAR (50)    NULL,
    [USER_PASSWORD]  VARCHAR (100)   NULL,
    [USER_MAIL]      VARCHAR (1000)  NOT NULL,
    [USER_NAISSANCE] DATE            NOT NULL,
    [IMG_PROFIL]     NVARCHAR (2000) NULL,
    [ID_CIVILITE]    INT             NOT NULL,
    CONSTRAINT [USERS_PK] PRIMARY KEY CLUSTERED ([ID_USER] ASC),
    CONSTRAINT [USERS_CIVILITE_FK] FOREIGN KEY ([ID_CIVILITE]) REFERENCES [dbo].[CIVILITE] ([ID_CIVILITE])
);



