/*------------------------------------------------------------
*        Script SQLSERVER 
------------------------------------------------------------*/
CREATE DATABASE MegaCastings
GO

USE MegaCastings
GO

/*------------------------------------------------------------
-- Table: CASTINGS
------------------------------------------------------------*/
CREATE TABLE CASTINGS(
	ID_CASTING          INT IDENTITY (1,1) NOT NULL ,
	LABEL               VARCHAR (50)  ,
	DOM_METIERS         VARCHAR (50)  ,
	METIERS             VARCHAR (50) NOT NULL ,
	TYPE_CONTRACT       VARCHAR (50) NOT NULL ,
	DUREE_DIFFUSION     INT   ,
	DATE_DEB_CONTRACT   DATETIME2 NOT NULL ,
	NB_POSTES           INT  NOT NULL ,
	LOCALISATION        VARCHAR (50) NOT NULL ,
	DESC_POSTE          TEXT   ,
	DESC_PROFIL         TEXT   ,
	COORDONNEES         VARCHAR (50)   ,
	CONSTRAINT CASTINGS_PK PRIMARY KEY (ID_CASTING)
);


/*------------------------------------------------------------
-- Table: PACK
------------------------------------------------------------*/
CREATE TABLE PACK(
	ID_PACK     INT IDENTITY (1,1) NOT NULL ,
	NAME_PACK   VARCHAR (50)  ,
	PRICE       INT    ,
	CONSTRAINT PACK_PK PRIMARY KEY (ID_PACK)
);


/*------------------------------------------------------------
-- Table: ORGANISATION
------------------------------------------------------------*/
CREATE TABLE ORGANISATION(
	ID_ORG       INT IDENTITY (1,1) NOT NULL ,
	NAME_ORG     VARCHAR (150) NOT NULL ,
	URL_ORG      VARCHAR (1000) NOT NULL ,
	EMAIL_ORG    VARCHAR (100)  ,
	TEL_ORG      VARCHAR (50) NOT NULL ,
	ADRESS_ORG   VARCHAR (100)  ,
	ID_CASTING   INT  NOT NULL ,
	ID_PACK      INT  NOT NULL  ,
	CONSTRAINT ORGANISATION_PK PRIMARY KEY (ID_ORG)

	,CONSTRAINT ORGANISATION_CASTINGS_FK FOREIGN KEY (ID_CASTING) REFERENCES CASTINGS(ID_CASTING)
	,CONSTRAINT ORGANISATION_PACK0_FK FOREIGN KEY (ID_PACK) REFERENCES PACK(ID_PACK)
);


/*------------------------------------------------------------
-- Table: CIVILITE
------------------------------------------------------------*/
CREATE TABLE CIVILITE(
	ID_CIVILITE      INT IDENTITY (1,1) NOT NULL ,
	LABEL_CIVILITE   VARCHAR (50) NOT NULL  ,
	CONSTRAINT CIVILITE_PK PRIMARY KEY (ID_CIVILITE)
);


/*------------------------------------------------------------
-- Table: USERS
------------------------------------------------------------*/
CREATE TABLE USERS(
	ID_USER          INT IDENTITY (1,1) NOT NULL ,
	USER_FIRSTNAME   VARCHAR (100)  ,
	USER_LASTNAME    VARCHAR (100) NOT NULL ,
	USERNAME         VARCHAR (50)  ,
	USER_PASSWORD    VARCHAR (100)  ,
	USER_MAIL        VARCHAR (1000) NOT NULL ,
	USER_NAISSANCE   DATETIME2 NOT NULL ,
	ID_CIVILITE      INT  NOT NULL  ,
	CONSTRAINT USERS_PK PRIMARY KEY (ID_USER)

	,CONSTRAINT USERS_CIVILITE_FK FOREIGN KEY (ID_CIVILITE) REFERENCES CIVILITE(ID_CIVILITE)
);


/*------------------------------------------------------------
-- Table: CATEGORIES
------------------------------------------------------------*/
CREATE TABLE CATEGORIES(
	ID_CAT      INT IDENTITY (1,1) NOT NULL ,
	CAT_LABEL   VARCHAR (50)   ,
	CONSTRAINT CATEGORIES_PK PRIMARY KEY (ID_CAT)
);


/*------------------------------------------------------------
-- Table: FILTRES
------------------------------------------------------------*/
CREATE TABLE FILTRES(
	ID_FILTRE      INT IDENTITY (1,1) NOT NULL ,
	CAT_LABEL      VARCHAR (50)  ,
	LABEL_FILTRE   VARCHAR (75) NOT NULL  ,
	CONSTRAINT FILTRES_PK PRIMARY KEY (ID_FILTRE)
);


/*------------------------------------------------------------
-- Table: POSTULER
------------------------------------------------------------*/
CREATE TABLE POSTULER(
	ID_CASTING   INT  NOT NULL ,
	ID_USER      INT  NOT NULL  ,
	CONSTRAINT POSTULER_PK PRIMARY KEY (ID_CASTING,ID_USER)

	,CONSTRAINT POSTULER_CASTINGS_FK FOREIGN KEY (ID_CASTING) REFERENCES CASTINGS(ID_CASTING)
	,CONSTRAINT POSTULER_USERS0_FK FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
);


/*------------------------------------------------------------
-- Table: APPARTIENT_CASTING
------------------------------------------------------------*/
CREATE TABLE APPARTIENT_CASTING(
	ID_CASTING   INT  NOT NULL ,
	ID_CAT       INT  NOT NULL  ,
	CONSTRAINT APPARTIENT_CASTING_PK PRIMARY KEY (ID_CASTING,ID_CAT)

	,CONSTRAINT APPARTIENT_CASTING_CASTINGS_FK FOREIGN KEY (ID_CASTING) REFERENCES CASTINGS(ID_CASTING)
	,CONSTRAINT APPARTIENT_CASTING_CATEGORIES0_FK FOREIGN KEY (ID_CAT) REFERENCES CATEGORIES(ID_CAT)
);


/*------------------------------------------------------------
-- Table: APPARTENIR_FILTRE
------------------------------------------------------------*/
CREATE TABLE APPARTENIR_FILTRE(
	ID_CASTING   INT  NOT NULL ,
	ID_FILTRE    INT  NOT NULL  ,
	CONSTRAINT APPARTENIR_FILTRE_PK PRIMARY KEY (ID_CASTING,ID_FILTRE)

	,CONSTRAINT APPARTENIR_FILTRE_CASTINGS_FK FOREIGN KEY (ID_CASTING) REFERENCES CASTINGS(ID_CASTING)
	,CONSTRAINT APPARTENIR_FILTRE_FILTRES0_FK FOREIGN KEY (ID_FILTRE) REFERENCES FILTRES(ID_FILTRE)
);


USE MegaCastings
GO


GO
SET IDENTITY_INSERT CIVILITE ON; 

INSERT INTO CIVILITE (ID_CIVILITE, LABEL_CIVILITE) VALUES (1, 'Monsieur');
INSERT INTO CIVILITE (ID_CIVILITE, LABEL_CIVILITE) VALUES (2, 'Madame');

GO
SET IDENTITY_INSERT CIVILITE OFF; 


GO
SET IDENTITY_INSERT USERS ON; 

insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (1, 'Blane', 'Woolmington', 'bwoolmington0', 'X7C1ef', 'bwoolmington0@elpais.com', '9/14/1970', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (2, 'Cacilia', 'Dachs', 'cdachs1', 'yZhNevy8l', 'cdachs1@mapy.cz', '6/27/1986', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (3, 'Annice', 'Firmage', 'afirmage2', 'mMaCIJ28', 'afirmage2@loc.gov', '7/13/1941', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (4, 'Hilde', 'Izhak', 'hizhak3', 'cIIswM', 'hizhak3@vkontakte.ru', '7/28/1953', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (5, 'Jasper', 'Felix', 'jfelix4', 'CdcKc5', 'jfelix4@tuttocitta.it', '1/23/1989', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (6, 'Donnajean', 'Jerrans', 'djerrans5', 'IH8Dxt9', 'djerrans5@princeton.edu', '12/19/1951', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (7, 'Carilyn', 'Root', 'croot6', 'QbRJVEBRQMmU', 'croot6@hao123.com', '5/9/1936', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (8, 'Kain', 'Huske', 'khuske7', 'MfbuYMaxVX3', 'khuske7@list-manage.com', '2/11/1987', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (9, 'Rosamond', 'Owttrim', 'rowttrim8', '1C06ybsvM29', 'rowttrim8@barnesandnoble.com', '10/19/1948', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (10, 'Phyllis', 'Lyman', 'plyman9', '2gTtmVrXxN', 'plyman9@wordpress.org', '10/18/1982', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (11, 'Erinna', 'Weir', 'eweira', 'nZevUg', 'eweira@chron.com', '10/21/1967', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (12, 'Murielle', 'Flade', 'mfladeb', 'N0GpraZUDwL', 'mfladeb@gravatar.com', '2/22/1968', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (13, 'Gusti', 'Roubeix', 'groubeixc', 'ZygKTFjfM', 'groubeixc@baidu.com', '4/3/1956', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (14, 'Zachery', 'McLernon', 'zmclernond', 'D7Xq32ZUBMBG', 'zmclernond@miitbeian.gov.cn', '2/2/1959', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (15, 'Tami', 'Thompson', 'tthompsone', 'aiMO1d08K', 'tthompsone@jalbum.net', '2/12/1939', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (16, 'Brendon', 'Fawckner', 'bfawcknerf', 'vG4OhAvhb', 'bfawcknerf@booking.com', '9/10/1972', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (17, 'Catherine', 'De Cruz', 'cdecruzg', 'pStExRhJpXJ', 'cdecruzg@php.net', '5/18/1973', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (18, 'Ted', 'Bilbey', 'tbilbeyh', 'CLuRsAED8', 'tbilbeyh@trellian.com', '4/23/1936', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (19, 'Drew', 'Osgorby', 'dosgorbyi', 'FxwUXaOD5s', 'dosgorbyi@dagondesign.com', '2/28/1975', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (20, 'Kellina', 'Le Noury', 'klenouryj', 'n1nYwC', 'klenouryj@biblegateway.com', '5/17/1941', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (21, 'Aurora', 'Idney', 'aidneyk', 'fUXSKehe7TYP', 'aidneyk@japanpost.jp', '4/27/1943', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (22, 'Annice', 'Callingham', 'acallinghaml', 'xKHYjqh', 'acallinghaml@cam.ac.uk', '6/30/1984', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (23, 'Gayelord', 'Dradey', 'gdradeym', 'CezGsPw6cc', 'gdradeym@fema.gov', '1/4/1954', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (24, 'Modesta', 'Pavia', 'mpavian', 'EulH4rb', 'mpavian@bing.com', '12/23/1984', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (25, 'Meris', 'Bonhill', 'mbonhillo', 'TmH64aF7', 'mbonhillo@prnewswire.com', '3/24/1970', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (26, 'Jenda', 'Rimes', 'jrimesp', 'io9S31Yn8S', 'jrimesp@topsy.com', '2/14/1970', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (27, 'Jana', 'Gatland', 'jgatlandq', 'FPOxgUn', 'jgatlandq@zimbio.com', '7/20/1969', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (28, 'Eduard', 'Davidowsky', 'edavidowskyr', 'ovrjQ5jd', 'edavidowskyr@soup.io', '11/29/1967', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (29, 'Leshia', 'Cordell', 'lcordells', 'Q60kZnL', 'lcordells@wikipedia.org', '12/17/1934', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (30, 'Fidel', 'Pikesley', 'fpikesleyt', 'UdBw5EdgYB2C', 'fpikesleyt@utexas.edu', '11/19/1985', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (31, 'Quill', 'de Zamora', 'qdezamorau', 'wcVp97eGq7', 'qdezamorau@phpbb.com', '12/23/1988', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (32, 'Rikki', 'O''Carney', 'rocarneyv', 'jYT8AGC', 'rocarneyv@bigcartel.com', '1/15/1954', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (33, 'Joyann', 'Ringsell', 'jringsellw', '014jwmz9k93M', 'jringsellw@cnbc.com', '8/16/1971', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (34, 'Faina', 'Mohammad', 'fmohammadx', 'yIi42Se', 'fmohammadx@usnews.com', '6/12/1958', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (35, 'Torry', 'Howell', 'thowelly', 'zJuHzFB', 'thowelly@topsy.com', '3/3/1937', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (36, 'Dari', 'O''Hannigan', 'dohanniganz', 'i7Rt4K4QY', 'dohanniganz@hugedomains.com', '9/1/1973', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (37, 'Cthrine', 'Hubback', 'chubback10', '1tlt2iORKWg', 'chubback10@over-blog.com', '11/27/1947', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (38, 'Bendicty', 'Drewry', 'bdrewry11', 'Jy5U50Dwm7', 'bdrewry11@cpanel.net', '10/20/1940', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (39, 'Aurelia', 'Chastel', 'achastel12', '0KRJsmbQL0S', 'achastel12@ed.gov', '4/13/1958', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (40, 'Flemming', 'Greggersen', 'fgreggersen13', 'xYavlC', 'fgreggersen13@360.cn', '4/13/1968', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (41, 'Fredek', 'Carter', 'fcarter14', 'UpnBndaiyobR', 'fcarter14@vinaora.com', '8/19/1972', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (42, 'Martynne', 'Berndtssen', 'mberndtssen15', 'K8Qy5I64iMxt', 'mberndtssen15@cbsnews.com', '6/14/1976', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (43, 'Donnajean', 'Dast', 'ddast16', '3kyM7ETzWLeR', 'ddast16@washington.edu', '12/1/1949', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (44, 'Jasun', 'Polkinhorn', 'jpolkinhorn17', 'aSIcf1p', 'jpolkinhorn17@google.it', '5/28/1970', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (45, 'Ferdinanda', 'Sukbhans', 'fsukbhans18', 'nAu7HFOpMh2', 'fsukbhans18@163.com', '9/11/1934', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (46, 'Marley', 'Dislee', 'mdislee19', '6aMnbzduaE', 'mdislee19@drupal.org', '1/3/1980', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (47, 'Rodina', 'Measom', 'rmeasom1a', 'CZsgToxejV5U', 'rmeasom1a@oaic.gov.au', '10/25/1977', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (48, 'Corine', 'Strick', 'cstrick1b', 'asIQfHILvt', 'cstrick1b@flavors.me', '5/3/1949', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (49, 'Edan', 'Tibbles', 'etibbles1c', 'wiI7QgHl9Ge', 'etibbles1c@technorati.com', '2/7/1983', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (50, 'Alexei', 'Harwood', 'aharwood1d', 'stpk9Tth', 'aharwood1d@webmd.com', '1/6/1968', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (51, 'Dionis', 'Wilse', 'dwilse1e', 'hFvyJ99Fz', 'dwilse1e@kickstarter.com', '5/2/1981', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (52, 'Bond', 'Greggersen', 'bgreggersen1f', '6WFQDAJtYt', 'bgreggersen1f@nydailynews.com', '4/16/1963', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (53, 'Woodrow', 'Clemot', 'wclemot1g', 'ZGMmJqF6rHU', 'wclemot1g@weibo.com', '2/12/1971', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (54, 'Malena', 'Prime', 'mprime1h', 'gaRGBGp', 'mprime1h@weebly.com', '3/21/1960', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (55, 'Larissa', 'Columbine', 'lcolumbine1i', 'Qwlt2EP', 'lcolumbine1i@ask.com', '12/24/1941', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (56, 'Wendeline', 'Schoales', 'wschoales1j', 'DchtoFO', 'wschoales1j@technorati.com', '4/9/1955', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (57, 'Brice', 'Longforth', 'blongforth1k', 'bFkjGCz7fc', 'blongforth1k@storify.com', '5/25/1939', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (58, 'Rici', 'Codner', 'rcodner1l', 'mwgUJxok4wgK', 'rcodner1l@princeton.edu', '10/29/1965', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (59, 'Chrissy', 'Dart', 'cdart1m', 'thBInf', 'cdart1m@rambler.ru', '11/10/1958', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (60, 'Faustina', 'Uren', 'furen1n', 'z5mkLfVYRvlw', 'furen1n@oaic.gov.au', '1/12/1980', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (61, 'Lexi', 'Basler', 'lbasler1o', 'jNyGOXgz', 'lbasler1o@rediff.com', '6/12/1988', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (62, 'Jackie', 'Ivanilov', 'jivanilov1p', 'TaTYNr', 'jivanilov1p@joomla.org', '7/27/1932', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (63, 'Debora', 'Vagg', 'dvagg1q', '9Gpngixd', 'dvagg1q@live.com', '5/8/1944', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (64, 'Findlay', 'Khalid', 'fkhalid1r', 'YPPZ2JU', 'fkhalid1r@foxnews.com', '9/28/1960', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (65, 'Krista', 'O''Corrane', 'kocorrane1s', 'Ht7DwMJKS7h', 'kocorrane1s@alibaba.com', '11/19/1969', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (66, 'Israel', 'Duro', 'iduro1t', 'nzZUzkrJX', 'iduro1t@about.me', '4/26/1958', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (67, 'Valenka', 'Bentje', 'vbentje1u', 'vklbscZw3mxQ', 'vbentje1u@moonfruit.com', '8/18/1951', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (68, 'Obie', 'Antoniewicz', 'oantoniewicz1v', 'RpZMLM', 'oantoniewicz1v@who.int', '4/18/1947', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (69, 'Brigitte', 'Clendennen', 'bclendennen1w', 'KKzW4qKOkwZs', 'bclendennen1w@meetup.com', '9/26/1945', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (70, 'Ive', 'Stoffels', 'istoffels1x', 'EpVBm2s', 'istoffels1x@icq.com', '4/25/1956', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (71, 'Fania', 'Seedhouse', 'fseedhouse1y', '3dGHHKK4Z65j', 'fseedhouse1y@telegraph.co.uk', '3/9/1946', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (72, 'Arabella', 'Simants', 'asimants1z', 'MdrbVv2', 'asimants1z@nymag.com', '2/8/1985', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (73, 'Shelli', 'Sexon', 'ssexon20', 'HtGUtJ', 'ssexon20@skype.com', '12/4/1981', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (74, 'Sasha', 'McQuillen', 'smcquillen21', 'nWk5CAO', 'smcquillen21@goo.ne.jp', '11/8/1941', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (75, 'Sigmund', 'Snoxall', 'ssnoxall22', 'sndD7CW', 'ssnoxall22@google.com', '4/14/1990', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (76, 'Izabel', 'Putland', 'iputland23', 'CNUuzUPRd', 'iputland23@hexun.com', '2/25/1948', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (77, 'Karisa', 'Legister', 'klegister24', 'LqV9lgEU5', 'klegister24@a8.net', '10/6/1937', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (78, 'Niles', 'Huyche', 'nhuyche25', 'p9VkD8XxyViD', 'nhuyche25@skype.com', '8/30/1974', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (79, 'Myrtie', 'Bohike', 'mbohike26', 'w6aOfQ32BcmP', 'mbohike26@examiner.com', '1/16/1950', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (80, 'Enrica', 'Gowanson', 'egowanson27', 'CG1VDh9x', 'egowanson27@google.de', '7/23/1981', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (81, 'Prentiss', 'Leatherland', 'pleatherland28', 'RRiKfHoz', 'pleatherland28@tinypic.com', '3/7/1934', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (82, 'Danya', 'Trollope', 'dtrollope29', 'L5YpHlg', 'dtrollope29@ow.ly', '11/22/1989', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (83, 'Bunni', 'Vian', 'bvian2a', '0Nko46Ele6e', 'bvian2a@cdbaby.com', '1/19/1933', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (84, 'Shannen', 'Redington', 'sredington2b', 'ieYZAehA', 'sredington2b@dion.ne.jp', '5/10/1936', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (85, 'Zacherie', 'Smallridge', 'zsmallridge2c', 'ITnrOQjckiv', 'zsmallridge2c@hubpages.com', '4/26/1932', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (86, 'Agathe', 'de Glanville', 'adeglanville2d', 'OKiuzaKPtA', 'adeglanville2d@youtube.com', '4/5/1966', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (87, 'Neill', 'Stidworthy', 'nstidworthy2e', '47lcEmOpY', 'nstidworthy2e@sakura.ne.jp', '4/25/1950', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (88, 'Andras', 'Lyon', 'alyon2f', 'j2uiQIz', 'alyon2f@meetup.com', '2/12/1954', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (89, 'Gerry', 'Stolz', 'gstolz2g', 'dH9Fij', 'gstolz2g@seesaa.net', '3/14/1959', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (90, 'Eve', 'Corke', 'ecorke2h', 'dkxusCdOmI1', 'ecorke2h@fda.gov', '6/24/1981', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (91, 'Tome', 'Pierce', 'tpierce2i', 'LftrFY', 'tpierce2i@examiner.com', '8/10/1987', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (92, 'Pat', 'Brunelli', 'pbrunelli2j', 'fHzaN5', 'pbrunelli2j@aboutads.info', '7/26/1988', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (93, 'Mirilla', 'Halbord', 'mhalbord2k', '9jRbBNl0P', 'mhalbord2k@about.me', '9/15/1941', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (94, 'Kelley', 'McFadyen', 'kmcfadyen2l', '1d1KfxsNP', 'kmcfadyen2l@about.com', '12/15/1962', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (95, 'Sandye', 'Fewings', 'sfewings2m', 'pQvKbAx', 'sfewings2m@topsy.com', '12/11/1955', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (96, 'Nedi', 'Wines', 'nwines2n', 'xPxxPZJNW', 'nwines2n@marriott.com', '6/11/1969', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (97, 'Laina', 'Keigher', 'lkeigher2o', 'JUP8KtyLYe', 'lkeigher2o@nps.gov', '3/26/1933', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (98, 'Garwood', 'Oldis', 'goldis2p', 'SJOlQJvaYeK', 'goldis2p@hubpages.com', '11/6/1933', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (99, 'Adara', 'McGuire', 'amcguire2q', 'YwbfaeZl', 'amcguire2q@networkadvertising.org', '11/22/1948', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (100, 'Georgia', 'Roscow', 'groscow2r', 'g3EQd4ZH', 'groscow2r@nsw.gov.au', '4/15/1962', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (101, 'Douglas', 'Jikylls', 'djikylls2s', 'BoBIU2Vl', 'djikylls2s@google.fr', '3/28/1952', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (102, 'Gustav', 'Sever', 'gsever2t', 'TIaWLIChoW', 'gsever2t@amazon.com', '5/28/1974', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (103, 'Francois', 'Gianelli', 'fgianelli2u', 'jI4gDeC', 'fgianelli2u@hibu.com', '9/2/1969', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (104, 'Ami', 'Cusack', 'acusack2v', 'CZQir9KiqFK', 'acusack2v@accuweather.com', '3/26/1980', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (105, 'Aron', 'Downer', 'adowner2w', 'x6uIHe0e5FB', 'adowner2w@amazon.co.jp', '3/12/1943', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (106, 'Quintana', 'Cearley', 'qcearley2x', '8RapASqwxJZ', 'qcearley2x@istockphoto.com', '1/26/1967', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (107, 'Carroll', 'More', 'cmore2y', 'SwQvEhByku', 'cmore2y@spotify.com', '10/10/1961', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (108, 'Becka', 'Dalby', 'bdalby2z', 'ulwEBWCSKn', 'bdalby2z@jimdo.com', '5/19/1970', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (109, 'Karl', 'Chisman', 'kchisman30', 'DX2TOUV', 'kchisman30@craigslist.org', '5/22/1942', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (110, 'Hetti', 'Sansam', 'hsansam31', 'OAPAcUKvo', 'hsansam31@slideshare.net', '1/19/1932', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (111, 'Emerson', 'Thistleton', 'ethistleton32', 'HukXigG4c', 'ethistleton32@aboutads.info', '7/20/1950', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (112, 'Pip', 'Ganforth', 'pganforth33', 'AdM7LhOen', 'pganforth33@google.com.au', '7/11/1950', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (113, 'Elspeth', 'Harden', 'eharden34', 'Ar02eabRDIe', 'eharden34@is.gd', '8/23/1953', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (114, 'Kaycee', 'Ladley', 'kladley35', 'snNwyVgMw', 'kladley35@comcast.net', '9/2/1985', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (115, 'Matty', 'Kramer', 'mkramer36', 'ozaR1FR', 'mkramer36@squarespace.com', '11/14/1963', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (116, 'Sorcha', 'Hedlestone', 'shedlestone37', 'xMyZrPy', 'shedlestone37@unicef.org', '5/16/1975', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (117, 'Norrie', 'Philler', 'nphiller38', 'DaGUOScjJ', 'nphiller38@oracle.com', '5/31/1934', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (118, 'Stephannie', 'Maris', 'smaris39', 'SKPW2k7vyvTQ', 'smaris39@angelfire.com', '8/20/1987', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (119, 'Luigi', 'Scanlon', 'lscanlon3a', 'Sx96CUL', 'lscanlon3a@google.ru', '7/30/1978', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (120, 'Cy', 'Alam', 'calam3b', '048gALdTwcf', 'calam3b@craigslist.org', '8/18/1961', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (121, 'Kin', 'Zuppa', 'kzuppa3c', 'llL1vp', 'kzuppa3c@reddit.com', '2/1/1977', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (122, 'Tammy', 'Stagg', 'tstagg3d', 'HRKrBcIw', 'tstagg3d@csmonitor.com', '8/5/1985', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (123, 'Beau', 'Brayshay', 'bbrayshay3e', '90nbI8', 'bbrayshay3e@independent.co.uk', '9/13/1951', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (124, 'Scot', 'Lillicrap', 'slillicrap3f', 'vhfShH', 'slillicrap3f@sbwire.com', '3/5/1965', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (125, 'Michele', 'Haxbie', 'mhaxbie3g', 'C42BZwZQK3', 'mhaxbie3g@imdb.com', '9/4/1985', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (126, 'Engracia', 'Toppas', 'etoppas3h', 'Qrg8Qcw', 'etoppas3h@fema.gov', '10/22/1930', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (127, 'Gilda', 'Shelmerdine', 'gshelmerdine3i', '2qW74eHuQXX5', 'gshelmerdine3i@kickstarter.com', '2/12/1982', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (128, 'Bren', 'Cressor', 'bcressor3j', 'ohNR72', 'bcressor3j@networkadvertising.org', '10/12/1944', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (129, 'Wit', 'Moppett', 'wmoppett3k', 'V3pLKTqLDI', 'wmoppett3k@whitehouse.gov', '11/29/1974', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (130, 'Nerta', 'Dupey', 'ndupey3l', 'q41aQnLf', 'ndupey3l@themeforest.net', '6/8/1987', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (131, 'Staffard', 'Charville', 'scharville3m', 'rAe0U95Lwxa0', 'scharville3m@spiegel.de', '3/28/1946', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (132, 'Flin', 'Greasty', 'fgreasty3n', 'Wsntc4', 'fgreasty3n@ihg.com', '10/9/1932', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (133, 'Juliann', 'L''Hommeau', 'jlhommeau3o', 'ecVFk2ujd', 'jlhommeau3o@wordpress.com', '3/29/1984', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (134, 'Lolita', 'Troppmann', 'ltroppmann3p', 'K5TuqT4bu', 'ltroppmann3p@acquirethisname.com', '11/7/1951', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (135, 'Lisa', 'Championnet', 'lchampionnet3q', 'VdMHpJYD', 'lchampionnet3q@intel.com', '5/19/1943', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (136, 'Roshelle', 'Kopfer', 'rkopfer3r', '5O0UWfPmEu8', 'rkopfer3r@sphinn.com', '4/4/1990', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (137, 'Rodge', 'Campsall', 'rcampsall3s', 'h0wIDQ4n', 'rcampsall3s@prlog.org', '4/12/1951', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (138, 'Cecilius', 'Baumann', 'cbaumann3t', 'DbjDgrUpAs1', 'cbaumann3t@tamu.edu', '10/10/1975', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (139, 'Harriette', 'Tenniswood', 'htenniswood3u', 'GSudlgh7Omt', 'htenniswood3u@constantcontact.com', '9/12/1939', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (140, 'Jodi', 'Pendre', 'jpendre3v', 'JLULRT', 'jpendre3v@goodreads.com', '3/5/1941', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (141, 'Goober', 'Limbrick', 'glimbrick3w', 'ZmN3ouia5CW', 'glimbrick3w@joomla.org', '11/6/1985', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (142, 'Genvieve', 'Durak', 'gdurak3x', 'CIidan', 'gdurak3x@rakuten.co.jp', '5/8/1931', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (143, 'Toiboid', 'Kahane', 'tkahane3y', '03SQXIjpWneo', 'tkahane3y@hc360.com', '3/17/1965', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (144, 'Asa', 'Qualtrough', 'aqualtrough3z', 'iSUi2sJ6t', 'aqualtrough3z@sbwire.com', '12/6/1946', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (145, 'Beverlee', 'Gerin', 'bgerin40', 'Eid5kiBAMRw', 'bgerin40@cbslocal.com', '1/24/1947', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (146, 'Hillier', 'Mathwen', 'hmathwen41', 'FT0smC4dBdl', 'hmathwen41@amazon.de', '1/16/1947', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (147, 'Auberon', 'Noke', 'anoke42', 'JQcEUt', 'anoke42@comsenz.com', '7/21/1938', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (148, 'Dody', 'Jedrychowski', 'djedrychowski43', 'QTSW5xV', 'djedrychowski43@google.cn', '12/22/1962', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (149, 'Nydia', 'Ridd', 'nridd44', 'YiuRoQ', 'nridd44@i2i.jp', '8/13/1969', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (150, 'Ronda', 'Hovey', 'rhovey45', 'd2BlBZLtGWq', 'rhovey45@geocities.jp', '12/17/1935', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (151, 'Lorry', 'Dukelow', 'ldukelow46', '9MKRN2rNS', 'ldukelow46@privacy.gov.au', '12/8/1938', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (152, 'Deirdre', 'Golthorpp', 'dgolthorpp47', 'PQqsdMm', 'dgolthorpp47@miibeian.gov.cn', '1/3/1965', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (153, 'Ginger', 'Chartre', 'gchartre48', 'XDg40XfZ8', 'gchartre48@ocn.ne.jp', '5/11/1966', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (154, 'Natalee', 'Doniso', 'ndoniso49', 'NqhslmrRCH', 'ndoniso49@newyorker.com', '9/5/1983', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (155, 'Valera', 'Viall', 'vviall4a', 'oY3AwIetcvN', 'vviall4a@fotki.com', '9/24/1990', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (156, 'Bruce', 'Harmson', 'bharmson4b', 'N9Loa013l5Mv', 'bharmson4b@cbsnews.com', '11/20/1947', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (157, 'Donny', 'Arnold', 'darnold4c', 'XTqfkKnC', 'darnold4c@shinystat.com', '11/12/1946', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (158, 'Dreddy', 'Orleton', 'dorleton4d', 'IjrxCZXA', 'dorleton4d@alexa.com', '1/27/1945', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (159, 'Myrta', 'Hully', 'mhully4e', 'W96dAVp2H1', 'mhully4e@meetup.com', '10/19/1961', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (160, 'Michal', 'Groombridge', 'mgroombridge4f', 'XrW9aQJ76', 'mgroombridge4f@fastcompany.com', '3/27/1976', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (161, 'Jessi', 'Crotty', 'jcrotty4g', 'j9Sh9TC6VX7i', 'jcrotty4g@reference.com', '4/9/1957', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (162, 'Udell', 'Matherson', 'umatherson4h', 'IIQVgPiKBcG', 'umatherson4h@springer.com', '7/23/1977', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (163, 'Sylas', 'Cruse', 'scruse4i', 'b4T1S0f7y', 'scruse4i@go.com', '9/18/1966', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (164, 'Goldia', 'McGahey', 'gmcgahey4j', '7bOLGLCWd5Q', 'gmcgahey4j@lulu.com', '4/25/1948', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (165, 'Hailee', 'Wass', 'hwass4k', 'EDUTnVoJ0', 'hwass4k@examiner.com', '3/20/1975', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (166, 'Andy', 'Krolak', 'akrolak4l', '0B4PzW4vBff', 'akrolak4l@nytimes.com', '8/2/1985', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (167, 'Daniel', 'Backman', 'dbackman4m', 'RJAeWm', 'dbackman4m@oracle.com', '2/7/1989', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (168, 'Silvia', 'Alessandrelli', 'salessandrelli4n', 'gZmIGq8L9d', 'salessandrelli4n@yolasite.com', '4/23/1981', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (169, 'Rachel', 'Boyle', 'rboyle4o', 'dxe3fPC', 'rboyle4o@123-reg.co.uk', '3/7/1990', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (170, 'Eloise', 'Pillington', 'epillington4p', 'e4Dj8m', 'epillington4p@vimeo.com', '10/31/1941', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (171, 'Brynne', 'Iddins', 'biddins4q', 'eIlJKr0ukx7I', 'biddins4q@xing.com', '8/7/1987', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (172, 'Gregoire', 'Seedull', 'gseedull4r', 'uilOL8mXBly', 'gseedull4r@ucla.edu', '1/12/1949', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (173, 'Toinette', 'Burner', 'tburner4s', '0M1R0Eg', 'tburner4s@ocn.ne.jp', '3/20/1984', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (174, 'Chantalle', 'Hebborn', 'chebborn4t', 'TCcsiU7Em', 'chebborn4t@multiply.com', '3/19/1965', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (175, 'Donal', 'Keeltagh', 'dkeeltagh4u', 'aeuGo9uz8P2', 'dkeeltagh4u@bigcartel.com', '9/12/1936', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (176, 'Helene', 'Collumbell', 'hcollumbell4v', 'VItP1ajTn', 'hcollumbell4v@pagesperso-orange.fr', '7/23/1935', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (177, 'Finn', 'Lakey', 'flakey4w', 'g5HY8sdwH8C', 'flakey4w@flavors.me', '11/10/1938', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (178, 'Kendall', 'Foro', 'kforo4x', 'VfohT1GI91', 'kforo4x@123-reg.co.uk', '4/24/1931', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (179, 'Norine', 'Ales0', 'nales4y', 'PrYBF8SjQ', 'nales4y@slideshare.net', '1/8/1963', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (180, 'Mitch', 'Masson', 'mmasson4z', 'nDLq0L9J', 'mmasson4z@linkedin.com', '7/24/1955', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (181, 'Kelsey', 'Taffs', 'ktaffs50', 'H5FousvjVy5', 'ktaffs50@ifeng.com', '12/11/1976', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (182, 'Jaquelyn', 'Gleasane', 'jgleasane51', 'lBmMPVVl', 'jgleasane51@foxnews.com', '10/29/1959', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (183, 'Forester', 'Lardner', 'flardner52', 'bsPdAIguFSeA', 'flardner52@sciencedirect.com', '4/22/1935', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (184, 'Ansel', 'Warland', 'awarland53', 'DHgpfZoN', 'awarland53@devhub.com', '1/23/1947', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (185, 'Gabbie', 'Cashmore', 'gcashmore54', 'wPUMKdcfQpD8', 'gcashmore54@clickbank.net', '9/11/1936', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (186, 'Faunie', 'Scrivenor', 'fscrivenor55', 'Ce6Aiw', 'fscrivenor55@desdev.cn', '12/14/1980', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (187, 'Worth', 'Hurt', 'whurt56', 'AzGeJyCy0mqw', 'whurt56@unblog.fr', '9/21/1965', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (188, 'Gordon', 'Gethings', 'ggethings57', 'PWphnybV', 'ggethings57@toplist.cz', '8/17/1947', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (189, 'Elisha', 'Brookwell', 'ebrookwell58', 'aLQu3cj', 'ebrookwell58@thetimes.co.uk', '6/9/1989', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (190, 'Tomkin', 'Bridges', 'tbridges59', 'hyc6lITOLBW', 'tbridges59@naver.com', '5/24/1956', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (191, 'Vivianne', 'Carnew', 'vcarnew5a', 'j3JRtRH5HOV', 'vcarnew5a@vk.com', '10/22/1966', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (192, 'Kermy', 'Mattheis', 'kmattheis5b', 'z9yjqKFCZw', 'kmattheis5b@fc2.com', '8/10/1940', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (193, 'Timi', 'Enrico', 'tenrico5c', '4hIfMxK6Ledr', 'tenrico5c@virginia.edu', '10/29/1963', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (194, 'Jory', 'Schieferstein', 'jschieferstein5d', 'EUpGFMx', 'jschieferstein5d@phpbb.com', '8/6/1986', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (195, 'Agnola', 'Rapps', 'arapps5e', '6Gfl97R', 'arapps5e@weebly.com', '9/20/1961', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (196, 'Joelynn', 'Stein', 'jstein5f', 'e4QM7So4DZ', 'jstein5f@mit.edu', '2/22/1972', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (197, 'Carleton', 'Strange', 'cstrange5g', '3WxEKX9nDx', 'cstrange5g@tinypic.com', '4/28/1953', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (198, 'Adam', 'Challoner', 'achalloner5h', 'fgSyU60wu', 'achalloner5h@ustream.tv', '8/17/1963', 1);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (199, 'Benedikta', 'Castagno', 'bcastagno5i', 'nszxCA', 'bcastagno5i@xinhuanet.com', '12/5/1956', 2);
insert into USERS (ID_USER, USER_FIRSTNAME, USER_LASTNAME, USERNAME, USER_PASSWORD, USER_MAIL, USER_NAISSANCE, ID_CIVILITE) values (200, 'Jena', 'Tew', 'jtew5j', 'c2G3Hjxl', 'jtew5j@earthlink.net', '2/6/1947', 2);


GO
SET IDENTITY_INSERT USERS OFF; 

GO
SET IDENTITY_INSERT CASTINGS ON; 

insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (1, 'Roe - White Fish', 'Energy', 'VP Accounting', 'Bitwolf', 4, '3/2/2021', 1, '71986 Delaware Point', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', '352-80-8086');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (2, 'Cookies - Englishbay Chochip', 'n/a', 'Project Manager', 'Holdlamis', 4, '9/1/2021', 10, '788 West Terrace', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '395-51-2804');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (3, 'Island Oasis - Ice Cream Mix', 'Consumer Non-Durables', 'Budget/Accounting Analyst I', 'Overhold', 2, '7/9/2021', 5, '196 Pankratz Place', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', '210-25-0687');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (4, 'Mustard - Dry, Powder', 'n/a', 'VP Quality Control', 'Mat Lam Tam', 1, '29/7/2020', 5, '53576 Hudson Drive', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Morbi non quam nec dui luctus rutrum.', '776-67-2028');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (5, 'Beans - Kidney, Canned', 'Basic Industries', 'VP Accounting', 'Latlux', 10, '22/10/2021', 5, '6137 Warbler Terrace', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', '230-67-0346');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (6, 'Soup V8 Roasted Red Pepper', 'n/a', 'Speech Pathologist', 'Solarbreeze', 10, '7/7/2021', 6, '66754 Del Mar Place', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '455-65-9074');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (7, 'Pasta - Penne, Lisce, Dry', 'n/a', 'GIS Technical Architect', 'Tin', 8, '1/7/2021', 1, '16 Pleasure Court', 'Maecenas pulvinar lobortis est.', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '480-48-6489');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (8, 'Raspberries - Frozen', 'Finance', 'Marketing Manager', 'Sonsing', 4, '5/11/2020', 6, '39 Morning Street', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', '554-89-4463');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (9, 'Bread - Bistro Sour', 'Consumer Services', 'Design Engineer', 'Matsoft', 1, '18/2/2021', 10, '82670 Westport Court', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '729-30-2169');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (10, 'Pork - Sausage Casing', 'Finance', 'Software Engineer I', 'Domainer', 5, '5/4/2020', 7, '1535 Nova Lane', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '746-95-3617');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (11, 'Cinnamon Buns Sticky', 'Consumer Services', 'Paralegal', 'Temp', 4, '29/11/2021', 3, '2158 Kennedy Alley', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', '621-84-9537');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (12, 'Bread - Bistro White', 'Energy', 'Design Engineer', 'Cookley', 5, '11/11/2021', 3, '672 Ronald Regan Alley', 'Mauris sit amet eros.', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', '267-38-3523');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (13, 'Canadian Emmenthal', 'Health Care', 'VP Product Management', 'Konklux', 2, '19/10/2020', 1, '51 Redwing Circle', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '586-76-3391');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (14, 'Sping Loaded Cup Dispenser', 'Basic Industries', 'Senior Developer', 'Wrapsafe', 3, '7/7/2020', 10, '3 Dayton Hill', 'Nunc rhoncus dui vel sem.', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', '229-07-9808');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (15, 'Cookie Dough - Chocolate Chip', 'Capital Goods', 'Health Coach IV', 'Lotlux', 2, '6/8/2021', 4, '2775 Russell Drive', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '582-31-6803');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (16, 'Oven Mitts 17 Inch', 'n/a', 'Biostatistician II', 'Flowdesk', 4, '22/3/2020', 5, '2996 Eastwood Pass', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '742-76-1415');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (17, 'Ice Cream - Fudge Bars', 'Consumer Non-Durables', 'Account Representative I', 'Toughjoyfax', 4, '5/12/2020', 4, '6360 Sunnyside Park', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', '596-85-6040');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (18, 'Lamb - Pieces, Diced', 'Basic Industries', 'Senior Quality Engineer', 'Y-find', 4, '25/5/2020', 6, '3199 Reindahl Street', 'Nam nulla.', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', '560-48-9349');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (19, 'Cups 10oz Trans', 'Capital Goods', 'Safety Technician III', 'Tin', 6, '15/10/2020', 9, '597 Bultman Point', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '197-21-7128');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (20, 'Soup - Campbells Tomato Ravioli', 'Consumer Services', 'Chief Design Engineer', 'Gembucket', 7, '22/12/2020', 8, '617 Surrey Place', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', '408-45-2882');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (21, 'Tart - Raisin And Pecan', 'Miscellaneous', 'Sales Associate', 'Zoolab', 6, '24/5/2020', 6, '53635 Northport Place', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', '152-68-8263');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (22, 'Pepper - Julienne, Frozen', 'Health Care', 'Senior Sales Associate', 'Biodex', 8, '14/12/2021', 5, '94518 Fair Oaks Hill', 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Suspendisse potenti.', '769-87-8928');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (23, 'Tray - 16in Rnd Blk', 'Capital Goods', 'Geologist III', 'Subin', 2, '23/12/2020', 3, '8189 Fieldstone Alley', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '831-57-2986');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (24, 'Mushroom - Crimini', 'Technology', 'Accountant II', 'Bamity', 10, '8/9/2021', 9, '00252 Sutherland Place', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', '812-82-5707');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (25, 'Pasta - Canelloni, Single Serve', 'n/a', 'Marketing Manager', 'Konklab', 7, '7/8/2020', 3, '60890 Loeprich Court', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', '411-64-0110');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (26, 'True - Vue Containers', 'Capital Goods', 'Biostatistician I', 'Voyatouch', 4, '21/7/2020', 10, '27 Pearson Trail', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', '193-69-3119');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (27, 'Squash - Guords', 'Technology', 'Financial Advisor', 'Bigtax', 10, '8/2/2021', 4, '60 Dottie Street', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '194-12-2021');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (28, 'Wine - Chablis 2003 Champs', 'n/a', 'VP Product Management', 'Lotlux', 5, '30/11/2020', 9, '0469 Brown Way', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '226-66-5671');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (29, 'Pork - Loin, Boneless', 'n/a', 'Web Developer IV', 'It', 8, '27/1/2020', 4, '7211 Northview Pass', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '742-06-5486');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (30, 'Savory', 'Basic Industries', 'Quality Control Specialist', 'Bamity', 6, '4/8/2020', 6, '57188 Anniversary Point', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '394-21-3191');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (31, 'Lid Tray - 16in Dome', 'n/a', 'Nuclear Power Engineer', 'Aerified', 6, '1/3/2020', 8, '7802 Waxwing Parkway', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Pellentesque ultrices mattis odio. Donec vitae nisi.', '571-18-3754');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (32, 'Pomello', 'Consumer Non-Durables', 'Desktop Support Technician', 'Home Ing', 10, '29/11/2021', 1, '0 Glacier Hill Terrace', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '741-03-7347');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (33, 'Cheese - Cheddar, Mild', 'Consumer Services', 'Dental Hygienist', 'Quo Lux', 1, '6/11/2019', 8, '197 Katie Way', 'Integer ac neque.', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '475-47-4332');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (34, 'Pasta - Detalini, White, Fresh', 'Health Care', 'Database Administrator IV', 'Holdlamis', 2, '22/8/2020', 10, '5395 Ridgeview Plaza', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '504-42-3414');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (35, 'Dried Figs', 'n/a', 'Accountant IV', 'Transcof', 7, '14/4/2020', 5, '7 Carberry Drive', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', '331-97-0964');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (36, 'Soup - Knorr, Chicken Noodle', 'Finance', 'Computer Systems Analyst IV', 'Lotlux', 3, '22/3/2020', 2, '3 Annamark Way', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '814-40-0372');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (37, 'Star Anise, Whole', 'Basic Industries', 'Data Coordiator', 'Mat Lam Tam', 7, '18/5/2020', 8, '24074 Esker Avenue', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '378-11-9320');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (38, 'Eggplant - Regular', 'Finance', 'Junior Executive', 'Konklux', 9, '28/3/2021', 3, '80151 Calypso Plaza', 'In congue. Etiam justo.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', '326-72-9557');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (39, 'Petit Baguette', 'Energy', 'Media Manager II', 'Andalax', 1, '2/5/2021', 10, '33 Lukken Alley', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', '523-74-8426');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (40, 'Seaweed Green Sheets', 'n/a', 'Assistant Media Planner', 'Lotstring', 10, '11/8/2021', 3, '954 Loomis Point', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '845-77-3341');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (41, 'Glass - Wine, Plastic, Clear 5 Oz', 'Technology', 'Recruiting Manager', 'Subin', 9, '16/3/2021', 7, '9400 Sycamore Plaza', 'Suspendisse potenti. Nullam porttitor lacus at turpis.', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '815-55-3577');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (42, 'Doilies - 5, Paper', 'n/a', 'Web Developer IV', 'Lotlux', 3, '24/8/2020', 5, '10 Armistice Park', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '344-77-7473');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (43, 'Oven Mitt - 13 Inch', 'Miscellaneous', 'Statistician I', 'Fixflex', 4, '23/12/2019', 10, '0446 Kingsford Crossing', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '800-29-1827');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (44, 'Beans - Yellow', 'Health Care', 'Data Coordiator', 'Flowdesk', 4, '22/6/2020', 5, '47 Twin Pines Parkway', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Nulla justo.', '341-49-3726');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (45, 'Wine - Alsace Riesling Reserve', 'Finance', 'Programmer Analyst I', 'Zoolab', 3, '29/5/2021', 3, '814 Messerschmidt Center', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '803-02-8272');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (46, 'Oil - Food, Lacquer Spray', 'Consumer Services', 'Human Resources Assistant III', 'Cardguard', 4, '11/9/2020', 4, '3497 Hanson Road', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', '266-74-6047');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (47, 'Syrup - Kahlua Chocolate', 'Consumer Services', 'Electrical Engineer', 'Job', 3, '19/1/2021', 4, '1565 Harper Center', 'Aliquam erat volutpat. In congue. Etiam justo.', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '285-65-0114');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (48, 'Napkin - Dinner, White', 'Consumer Services', 'Chief Design Engineer', 'Domainer', 1, '28/4/2020', 2, '7232 School Terrace', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', '756-97-9652');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (49, 'Pastry - Cheese Baked Scones', 'n/a', 'Professor', 'Lotstring', 1, '10/10/2020', 3, '6492 Shopko Pass', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '154-51-3174');
insert into Castings (ID_CASTING, LABEL, DOM_METIERS, METIERS, TYPE_CONTRACT, DUREE_DIFFUSION, DATE_DEB_CONTRACT, NB_POSTES, LOCALISATION, DESC_POSTE, DESC_PROFIL, COORDONNEES) values (50, 'Puree - Kiwi', 'Technology', 'Analog Circuit Design manager', 'Asoka', 2, '25/10/2020', 2, '00 Manitowish Parkway', 'Phasellus in felis.', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', '644-89-8769');

GO
SET IDENTITY_INSERT CASTINGS OFF; 

GO
SET IDENTITY_INSERT PACK ON;

insert into PACK (ID_PACK, NAME_PACK, PRICE) values (1, 'Fix San', 156);
insert into PACK (ID_PACK, NAME_PACK, PRICE) values (2, 'Mat Lam Tam', 304);
insert into PACK (ID_PACK, NAME_PACK, PRICE) values (3, 'Zoolab', 342);

GO
SET IDENTITY_INSERT PACK OFF;

GO
SET IDENTITY_INSERT ORGANISATION ON;


insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (1, 'Linklinks', 'nsw.gov.au', 'jdarree0@flavors.me', '261-270-6968', '458 Moland Parkway', 1, 47);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (2, 'Skimia', 'multiply.com', 'bgorges1@statcounter.com', '416-128-8809', '6 Beilfuss Junction', 3, 28);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (3, 'Twinte', 'eepurl.com', 'cegan2@shareasale.com', '981-710-7576', '8705 Michigan Alley', 2, 31);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (4, 'Kazio', 'ning.com', 'abrandreth3@live.com', '455-572-4755', '72320 Kenwood Junction', 3, 21);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (5, 'Jetpulse', 'yolasite.com', 'llavall4@nsw.gov.au', '467-812-4846', '1696 Prairieview Crossing', 2, 10);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (6, 'Dabfeed', 'illinois.edu', 'hwimmers5@mapy.cz', '798-105-3276', '09 Forest Run Court', 3, 46);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (7, 'Yadel', 'cafepress.com', 'ggeratt6@cnn.com', '471-715-4105', '813 Kenwood Way', 2, 19);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (8, 'Photolist', 'indiegogo.com', 'sstrowther7@unesco.org', '842-158-4189', '58 Glacier Hill Hill', 2, 17);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (9, 'Roombo', 'trellian.com', 'spilmore8@dion.ne.jp', '613-962-0496', '49 Glendale Crossing', 1, 11);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (10, 'Quatz', 'example.com', 'wkenright9@yale.edu', '427-418-2650', '1200 Spohn Alley', 1, 14);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (11, 'Zazio', 'who.int', 'ebelhomea@tuttocitta.it', '307-887-7735', '63 Sherman Way', 1, 28);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (12, 'Oyoba', 'vkontakte.ru', 'kbonessb@imdb.com', '532-747-9023', '17 Springs Parkway', 3, 26);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (13, 'Mynte', 'xrea.com', 'nthorndalec@wikispaces.com', '966-435-2332', '0 Kinsman Avenue', 3, 23);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (14, 'Kamba', 'bloomberg.com', 'pbrouwerd@instagram.com', '768-477-9237', '6 Forster Place', 3, 24);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (15, 'Feedfish', 'latimes.com', 'cblanninge@cnn.com', '353-628-3113', '491 Tennyson Center', 3, 27);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (16, 'Skyndu', 'youku.com', 'cmccambroisf@mlb.com', '931-493-2440', '435 Killdeer Hill', 2, 49);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (17, 'Skyndu', 'jugem.jp', 'gbraggg@google.com.hk', '939-625-0198', '1 Anzinger Trail', 3, 42);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (18, 'Mynte', 'rediff.com', 'adowglassh@tuttocitta.it', '231-277-0163', '6 Killdeer Terrace', 2, 30);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (19, 'Yotz', 'bing.com', 'khawkinsi@wikia.com', '604-869-1968', '608 Boyd Crossing', 2, 4);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (20, 'Eabox', 'myspace.com', 'nfranceyj@1688.com', '395-531-3126', '5 Ridge Oak Terrace', 2, 43);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (21, 'Buzzdog', 'fda.gov', 'jvasenink@instagram.com', '265-840-2185', '4 Heffernan Street', 1, 38);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (22, 'Livetube', 'tumblr.com', 'eleahl@ameblo.jp', '292-605-8729', '86 Mayfield Junction', 2, 39);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (23, 'Rhyzio', 'forbes.com', 'aharversonm@hubpages.com', '980-239-3627', '627 Harbort Plaza', 1, 37);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (24, 'Twimm', 'tamu.edu', 'wgutierrezn@mozilla.org', '619-325-9636', '1796 Cherokee Trail', 1, 3);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (25, 'Roodel', 'sfgate.com', 'oashfieldo@indiatimes.com', '362-390-9298', '2 Steensland Street', 3, 11);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (26, 'Gabtune', 'harvard.edu', 'rsabaterp@usnews.com', '740-197-5362', '747 Ramsey Place', 1, 30);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (27, 'Quaxo', 'umich.edu', 'cwilemanq@homestead.com', '786-232-6639', '4328 Ruskin Point', 1, 32);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (28, 'Agimba', 'surveymonkey.com', 'zfranchyonokr@google.de', '621-786-2395', '70338 Hudson Place', 1, 34);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (29, 'Yakidoo', 'skyrock.com', 'spatiss@utexas.edu', '451-971-6261', '92 Artisan Crossing', 2, 36);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (30, 'Browsedrive', 'google.nl', 'apatinkint@bigcartel.com', '843-518-7584', '606 Moose Trail', 3, 14);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (31, 'Wordtune', 'ted.com', 'pmcreedyu@unesco.org', '471-991-7176', '40 Carey Trail', 1, 19);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (32, 'Skippad', 'craigslist.org', 'mpoveyv@networksolutions.com', '902-255-7657', '423 Ohio Crossing', 2, 36);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (33, 'Yambee', 'blogger.com', 'vprobyw@cornell.edu', '246-778-9322', '5765 Shoshone Parkway', 1, 23);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (34, 'Devbug', 'ifeng.com', 'ahaighx@google.es', '184-476-8165', '9 Knutson Pass', 3, 20);
insert into ORGANISATION (ID_ORG, NAME_ORG, URL_ORG, EMAIL_ORG, TEL_ORG, ADRESS_ORG, ID_PACK, ID_CASTING) values (35, 'Zoonder', 'youtube.com', 'bcattelly@tiny.cc', '718-139-4484', '2597 Knutson Point', 1, 49);

GO
SET IDENTITY_INSERT ORGANISATION OFF;

GO
SET IDENTITY_INSERT CATEGORIES ON;

insert into CATEGORIES (ID_CAT, CAT_LABEL) values (1, 'Cinema');
insert into CATEGORIES (ID_CAT, CAT_LABEL) values (2, 'Musique');
insert into CATEGORIES (ID_CAT, CAT_LABEL) values (3, 'Theatre');
insert into CATEGORIES (ID_CAT, CAT_LABEL) values (4, 'Publicité');

GO
SET IDENTITY_INSERT CATEGORIES OFF;