DROP TABLE POSTULER
DROP TABLE APPARTIENT_CASTING
GO

DROP TABLE IF EXISTS USERS

GO

CREATE TABLE USERS(
	ID_USER          INT  NOT NULL ,
	USER_FIRSTNAME   VARCHAR (100)  ,
	USER_LASTNAME    VARCHAR (100) NOT NULL ,
	USERNAME         VARCHAR (50)  ,
	USER_PASSWORD    VARCHAR (100)  ,
	USER_MAIL        VARCHAR (1000) NOT NULL ,
	USER_NAISSANCE   DATE NOT NULL ,
	IMG_PROFIL       NVARCHAR (2000) ,
	ID_CIVILITE      INT  NOT NULL  ,
	CONSTRAINT USERS_PK PRIMARY KEY (ID_USER)

	,CONSTRAINT USERS_CIVILITE_FK FOREIGN KEY (ID_CIVILITE) REFERENCES CIVILITE(ID_CIVILITE)
);

GO

DROP TABLE IF EXISTS CATEGORIES
GO

CREATE TABLE CATEGORIES(
	ID_CAT      INT IDENTITY (1,1) NOT NULL ,
	CAT_LABEL   VARCHAR (50)  ,
	IMG_CAST    NVARCHAR (2000) NULL ,
	CONSTRAINT CATEGORIES_PK PRIMARY KEY (ID_CAT)
);


GO

CREATE TABLE APPARTIENT_CASTING(
	ID_CASTING   INT  NOT NULL ,
	ID_CAT       INT  NOT NULL  ,
	CONSTRAINT APPARTIENT_CASTING_PK PRIMARY KEY (ID_CASTING,ID_CAT)

	,CONSTRAINT APPARTIENT_CASTING_CASTINGS_FK FOREIGN KEY (ID_CASTING) REFERENCES CASTINGS(ID_CASTING)
	,CONSTRAINT APPARTIENT_CASTING_CATEGORIES0_FK FOREIGN KEY (ID_CAT) REFERENCES CATEGORIES(ID_CAT)
);

GO

CREATE TABLE POSTULER(
	ID_CASTING   INT  NOT NULL ,
	ID_USER      INT  NOT NULL  ,
	CONSTRAINT POSTULER_PK PRIMARY KEY (ID_CASTING,ID_USER)

	,CONSTRAINT POSTULER_CASTINGS_FK FOREIGN KEY (ID_CASTING) REFERENCES CASTINGS(ID_CASTING)
	,CONSTRAINT POSTULER_USERS0_FK FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
);
